server:
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/,http://eureka-server-7003:7003/eureka/
  instance:
    instance-id: eureka-consumer-hystrix-dashbord-10001 # 服务名称
    prefer-ip-address: true # 显示ip地址

info: # 点击注册列表未服务出现的信息
  app.name: springcloud
  company.name: www.honor.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@

spring:
  application:
    name: eureka-consumer-hystrix-dashbord

turbine:
  combine-host-port: true
  app-config: EUREKA-CONSUMER #需要监控的集群名称
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")