server:
  port: 7001

eureka:
  instance:
    hostname: eureka-server-7001
  client:
    registerWithEureka: false #false表示不向注册中心注册自己。
    fetchRegistry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://eureka-server-7002:7002/eureka/,http://eureka-server-7003:7003/eureka/
#      defaultZone: http://eureka-server-7001:7001/eureka/